#!/usr/bin/env node

const fetch = require("node-fetch");
const yargs = require("yargs");

const argv = yargs
  .example("./scrape_crowdfunder [options] http://example.com/projects")
  .option("verbose", {
    alias: "v",
    description: "Run verbosely",
    type: "boolean"
  })
  .hide("version")
  .help()
  .alias("help", "h").argv;

const verbose = argv.verbose;
const index_url = argv._[0];

function abort(message) {
  process.stderr.write(message + "\n");
  process.exit(1);
}

async function getIndex(url, verbose) {
  if (verbose) {
    process.stdout.write(`Fetching: GET ${url} ... `);
  }
  const index_res = await fetch(index_url);
  const status = index_res.status;
  const index_html = await index_res.text();
  if (verbose) {
    console.log(`status ${status}, ${index_html.length} bytes`);
  }
  if (status === 200) {
    console.log("now parsing");
  } else {
    abort(`Projects page returned HTTP ${status} - Is the site down? Check the URL given?`);
  }
}

if (index_url) {
  getIndex(index_url, verbose);
} else {
  abort("Please provide the url of the list of campaigns, i.e. './scrape_crowdfunder http://example.com/projects'");
}
